import { useEffect, useMemo, useState } from 'react';
import { api, clearAppToken, getAppToken, setAppToken, type ApiRecord, type Bootstrap, type TaskFields } from './lib/api';
import { buildPlan, type DayPlan, type PlanTask } from './lib/planEngine';

const today = new Date().toISOString().slice(0, 10);
const text = (value: unknown) => Array.isArray(value) ? String(value[0] ?? '') : String(value ?? '');
const phaseName = (phaseId: string | undefined, phases: ApiRecord[]) => phases.find((phase) => phase.id === phaseId)?.fields.name as string | undefined;
const dateLabel = (day: string) => new Intl.DateTimeFormat('fr-FR', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(`${day}T12:00:00Z`));
const hours = (value: number) => `${Number.isInteger(value) ? value : value.toFixed(1).replace('.', ',')} h`;

function CapacityDial({ value, committed, template, size = 'lg', onChange, readOnly = false }: { value: number; committed: number; template: number; size?: 'lg' | 'md' | 'sm'; onChange?: (hours: number) => void; readOnly?: boolean }) {
  const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]);
  const diameter = size === 'lg' ? 200 : size === 'md' ? 120 : 56; const r = 39; const circumference = 2 * Math.PI * r * .75;
  const snap = (next: number) => Math.max(0, Math.min(12, Math.round(next * 2) / 2));
  const fromPointer = (event: React.PointerEvent<SVGSVGElement>) => { const box = event.currentTarget.getBoundingClientRect(); const x = ((event.clientX - box.left) / box.width) * 100 - 50; const y = ((event.clientY - box.top) / box.height) * 100 - 50; let angle = Math.atan2(y, x) * 180 / Math.PI; if (angle < 135) angle += 360; return snap(((angle - 135) / 270) * 12); };
  const commit = (next: number) => { const value = snap(next); setDraft(value); onChange?.(value); };
  const budgetLength = circumference * (draft / 12); const committedLength = circumference * Math.min(1, committed / 12); const ratio = value ? committed / value : committed ? Infinity : 0;
  return <div className={`dial dial-${size}`} style={{ width: diameter }}><svg viewBox="0 0 100 100" role="slider" aria-valuemin={0} aria-valuemax={12} aria-valuenow={draft} aria-label="Heures disponibles" tabIndex={readOnly ? -1 : 0} onPointerDown={(event) => { if (readOnly) return; event.currentTarget.setPointerCapture(event.pointerId); setDraft(fromPointer(event)); }} onPointerMove={(event) => { if (!readOnly && event.currentTarget.hasPointerCapture(event.pointerId)) setDraft(fromPointer(event)); }} onPointerUp={(event) => { if (!readOnly) commit(fromPointer(event)); }} onWheel={(event) => { if (!readOnly) { event.preventDefault(); commit(draft + (event.deltaY > 0 ? -.5 : .5)); } }} onKeyDown={(event) => { if (readOnly) return; if (event.key === 'ArrowUp') commit(draft + (event.shiftKey ? 1 : .5)); if (event.key === 'ArrowDown') commit(draft - (event.shiftKey ? 1 : .5)); if (event.key === 'Home') commit(0); if (event.key === 'End') commit(template); }}>
    <path className="dial-track" d="M 22.4 77.6 A 39 39 0 1 1 77.6 77.6" fill="none" pathLength="100" />
    <path className="dial-budget" d="M 22.4 77.6 A 39 39 0 1 1 77.6 77.6" fill="none" pathLength="100" strokeDasharray={`${draft / 12 * 100} 100`} />
    <path className={`dial-committed ${ratio > 1 ? 'over' : ratio >= .9 ? 'tight' : ''}`} d="M 28 72 A 31 31 0 1 1 72 72" fill="none" pathLength="100" strokeDasharray={`${Math.min(1, committed / 12) * 100} 100`} />
  </svg>{size !== 'sm' && <div className="dial-value"><b>{hours(draft)}</b><small>{hours(committed)} engagées</small></div>}</div>;
}

function Login({ onReady }: { onReady: () => void }) { const [token, setToken] = useState(''); return <main className="login"><section><span className="mark">◒</span><h1>Cadence</h1><p>Entre le token d’accès de ton espace une seule fois. Il reste uniquement dans ce navigateur.</p><form onSubmit={(event) => { event.preventDefault(); if (token.trim()) { setAppToken(token); onReady(); } }}><input autoFocus value={token} onChange={(event) => setToken(event.target.value)} placeholder="App token" type="password"/><button className="primary">Ouvrir Cadence</button></form></section></main>; }

function DayList({ day, tasks, phases, pin, openPhase }: { day: DayPlan; tasks: ApiRecord<TaskFields>[]; phases: ApiRecord[]; pin: (task: ApiRecord<TaskFields>) => void; openPhase: (id: string) => void }) { const scheduled = day.items.filter((item) => ['scheduled', 'pinned', 'split'].includes(item.state)); const deferred = day.items.filter((item) => !['scheduled', 'pinned', 'split'].includes(item.state)); const row = (item: DayPlan['items'][number]) => { const task = tasks.find((candidate) => candidate.id === item.taskId); if (!task) return null; const phase = task.fields.phase?.[0]; return <article className="plan-row" key={`${item.taskId}-${item.segmentIndex ?? 0}`}><div><b>{task.fields.name}</b><div className="row-meta">{phase && <button className="phase-chip" onClick={() => openPhase(phase)}>{phaseName(phase, phases) ?? 'Phase'}</button>}{item.isUnestimated && <span>Non chiffrée</span>}{item.segmentCount && <span>Jour {item.segmentIndex}/{item.segmentCount}</span>}</div></div><div className="row-right"><strong>{hours(item.costHours)}</strong><button title="Forcer aujourd’hui" className="pin" onClick={() => pin(task)}>⌖</button>{item.state === 'late' ? <em className="late">En retard</em> : item.state === 'deferred' ? <em className="deferred">Reportée au {item.originalDay ? '' : ''}{item.state && day.day}</em> : item.state === 'unplannable' ? <em>Non planifiable</em> : null}</div></article>; };
  return <section className="day-list"><h3>Au programme <span>{scheduled.length}</span></h3>{scheduled.length ? scheduled.map(row) : <p className="empty">Aucune tâche planifiée.</p>}<details open={deferred.some((item) => item.state === 'late')}><summary>Ne rentre pas aujourd’hui <span>{deferred.length}</span></summary>{deferred.map(row)}</details></section>; }

function PhaseSheet({ phaseId, phases, tasks, close, reload }: { phaseId: string | null; phases: ApiRecord[]; tasks: ApiRecord<TaskFields>[]; close: () => void; reload: () => Promise<void> }) { if (!phaseId) return null; const phase = phases.find((item) => item.id === phaseId); const entries = tasks.filter((task) => task.fields.phase?.includes(phaseId)); const toggle = async (task: ApiRecord<TaskFields>) => { await api.update('Tasks', task.id, { status: task.fields.status === 'Terminé' ? 'Backlog' : 'Terminé', completedAt: task.fields.status === 'Terminé' ? undefined : today }); await reload(); };
 return <aside className="phase-sheet"><header><div><small>{text(phase?.fields.project) || 'Périmètre'}</small><h2>{text(phase?.fields.name)}</h2></div><button onClick={close}>×</button></header><p>{entries.filter((task) => task.fields.status === 'Terminé').length}/{entries.length} tâches · {hours(entries.reduce((sum, task) => sum + Math.max(0, Number(task.fields.estimatedHours ?? task.fields.legacyEstimateHours ?? 1) - Number(task.fields.loggedHours ?? 0)), 0))} restantes</p><div>{entries.map((task) => <label className="phase-task" key={task.id}><input type="checkbox" checked={task.fields.status === 'Terminé'} onChange={() => void toggle(task)}/><span>{task.fields.name}</span><small>{hours(Number(task.fields.estimatedHours ?? task.fields.legacyEstimateHours ?? 1))}</small></label>)}</div></aside>; }

function Resources({ data, plan, capacity, setCapacity, openPhase }: { data: Bootstrap; plan: DayPlan[]; capacity: Record<string, number>; setCapacity: (day: string, value: number) => void; openPhase: (id: string) => void }) { const template = Object.fromEntries(data['Capacity Template'].map((row) => [Number(row.fields.index), Number(row.fields.hours ?? 0)])); const start = plan.slice(0, 7); const total = start.reduce((sum, day) => sum + day.committedHours, 0); const available = start.reduce((sum, day) => sum + day.capacityHours, 0); return <main className="page resources"><div className="page-bar"><div><button className="crumb" onClick={() => history.pushState({}, '', '/')}><span>←</span> Cockpit</button><h1>Ressources</h1><p>{hours(total)} engagées / {hours(available)} disponibles cette semaine</p></div></div><section className="week-grid">{start.map((day) => <article className="week-day" key={day.day}><b>{dateLabel(day.day)}</b><CapacityDial value={day.capacityHours} committed={day.committedHours} template={template[new Date(`${day.day}T12:00:00Z`).getDay()] ?? 8} size="md" onChange={(value) => setCapacity(day.day, value)}/><strong className={day.state}>{hours(day.committedHours)} / {hours(day.capacityHours)}</strong><small>{day.items.length} tâches</small>{capacity[day.day] !== undefined && <button className="link" onClick={() => setCapacity(day.day, template[new Date(`${day.day}T12:00:00Z`).getDay()] ?? 8)}>Rétablir la semaine type</button>}</article>)}</section><details className="template"><summary>Semaine type</summary><div className="week-grid">{data['Capacity Template'].sort((a, b) => Number(a.fields.index) - Number(b.fields.index)).map((row) => <article className="week-day" key={row.id}><b>{['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'][Number(row.fields.index)]}</b><CapacityDial value={Number(row.fields.hours ?? 0)} committed={0} template={Number(row.fields.hours ?? 0)} size="md" onChange={(value) => void api.update('Capacity Template', row.id, { hours: value }).then(() => location.reload())}/></article>)}</div></details></main>; }

export default function App() { const [data, setData] = useState<Bootstrap | null>(null); const [error, setError] = useState(''); const [phaseId, setPhaseId] = useState<string | null>(new URLSearchParams(location.search).get('phase')); const resources = location.pathname === '/ressources'; const load = async () => { try { setData(await api.bootstrap()); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Synchronisation Airtable impossible'); } }; useEffect(() => { if (getAppToken()) void load(); const pop = () => setPhaseId(new URLSearchParams(location.search).get('phase')); addEventListener('popstate', pop); return () => removeEventListener('popstate', pop); }, []);
 if (!getAppToken()) return <Login onReady={() => void load()}/>; if (!data) return <div className="loading">Chargement de ton espace… {error}</div>;
 const template = Object.fromEntries(data['Capacity Template'].map((row) => [Number(row.fields.index), Number(row.fields.hours ?? 0)])); const settings = Object.fromEntries(data.Settings.map((row) => [String(row.fields.key), Number(row.fields.value)])); const capacity = Object.fromEntries(data['Day Capacity'].map((row) => [String(row.fields.day ?? row.fields.key), Number(row.fields.hours)])); const tasks: PlanTask[] = data.Tasks.map((task) => ({ id: task.id, name: String(task.fields.name ?? ''), status: String(task.fields.status ?? ''), priority: (task.fields.priority ?? 'P2') as PlanTask['priority'], estimatedHours: Number(task.fields.estimatedHours ?? task.fields.legacyEstimateHours ?? 0), loggedHours: Number(task.fields.loggedHours ?? 0), pinnedDay: task.fields.pinnedDay, dueDate: task.fields.dueDate, createdAt: task.createdTime, displayOrder: Number(task.fields.displayOrder ?? 0), capacityExempt: Boolean(task.fields.capacityExempt), isGroup: Boolean(task.fields.children?.length) })); const plan = buildPlan(tasks, capacity, Array.from({ length: 7 }, (_, index) => template[index] ?? (index === 0 || index === 6 ? 0 : 8)), { defaultDayHours: settings.default_day_hours || 8, defaultTaskHours: settings.default_task_hours || 1, spillHorizonDays: settings.spill_horizon_days || 90 }, today); const current = plan[0]; const setCapacity = async (day: string, value: number) => { const existing = data['Day Capacity'].find((row) => String(row.fields.day ?? row.fields.key) === day); const next = { ...data, 'Day Capacity': existing ? data['Day Capacity'].map((row) => row.id === existing.id ? { ...row, fields: { ...row.fields, hours: value } } : row) : [...data['Day Capacity'], { id: `optimistic-${day}`, fields: { key: day, day, hours: value } }] }; setData(next); try { if (value === (template[new Date(`${day}T12:00:00Z`).getDay()] ?? 8) && existing) await api.remove('Day Capacity', existing.id); else await api.upsert('Day Capacity', [{ fields: { key: day, day, hours: value } }], ['key']); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Écriture impossible'); await load(); } }; const openPhase = (id: string) => { history.pushState({}, '', `${location.pathname}?phase=${id}`); setPhaseId(id); }; const closePhase = () => { history.back(); setPhaseId(null); }; const pin = (task: ApiRecord<TaskFields>) => void api.update('Tasks', task.id, { pinnedDay: today }).then(load).catch((cause) => setError(String(cause)));
 if (resources) return <><Resources data={data} plan={plan} capacity={capacity} setCapacity={setCapacity} openPhase={openPhase}/><PhaseSheet phaseId={phaseId} phases={data.Phases} tasks={data.Tasks} close={closePhase} reload={load}/></>;
 return <div className="product"><header><button className="logo" onClick={() => location.reload()}>◒</button><div className="head-title"><b>Cadence</b><span>Ton cockpit d’exécution</span></div><div className="head-right"><button className="link" onClick={() => { clearAppToken(); location.reload(); }}>Déconnecter</button><button className="icon" onClick={() => void load()}>↻</button></div></header>{error && <div className="error">{error}</div>}<main className="page"><div className="page-bar"><div><h1>Bonjour Gabriel</h1><p>Le plan exécutable, pas la liste infinie.</p></div><button className="secondary" onClick={() => { history.pushState({}, '', '/ressources'); location.reload(); }}>Gérer la semaine →</button></div><section className="day-card"><CapacityDial value={current.capacityHours} committed={current.committedHours} template={template[new Date(`${today}T12:00:00Z`).getDay()] ?? 8} onChange={(value) => void setCapacity(today, value)}/><div><small>{dateLabel(today)}</small><h2 className={current.state}>{hours(current.committedHours)} / {hours(current.capacityHours)}</h2><progress max={Math.max(current.capacityHours, current.committedHours, 1)} value={current.committedHours}/><p>{current.items.filter((item) => ['scheduled', 'pinned', 'split'].includes(item.state)).length} au programme · {current.items.filter((item) => item.state === 'deferred').length} reportées · {current.items.filter((item) => item.state === 'late').length} en retard</p><button className="preset" onClick={() => void setCapacity(today, 0)}>Bureau</button><button className="preset" onClick={() => void setCapacity(today, 4)}>Demi</button><button className="preset" onClick={() => void setCapacity(today, template[new Date(`${today}T12:00:00Z`).getDay()] ?? 8)}>Normale</button></div></section><DayList day={current} tasks={data.Tasks} phases={data.Phases} pin={pin} openPhase={openPhase}/></main><PhaseSheet phaseId={phaseId} phases={data.Phases} tasks={data.Tasks} close={closePhase} reload={load}/></div>; }
